config/routes.rb
Rails.application.routes.draw do
  resources :scraps, only: [:index, :create]
  resources :searches, only: [:index, :create]
  root to: 'scraps#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scraps_controller.rb
require 'httparty'

class ScrapsController < ApplicationController
  def index
    if search_params_present?
      api_key = ENV['GOOGLE_API_KEY']
      cse_id = ENV['GOOGLE_CSE_ID']
      keywords = [params[:keyword_1], params[:keyword_2], params[:keyword_3]].join(' ')

      response = HTTParty.get("https://www.googleapis.com/customsearch/v1", query: {
        key: api_key,
        cx: cse_id,
        q: keywords
      })

      @results = response.parsed_response if response.code == 200
    end
  end

  private

  def search_params_present?
    params[:keyword_1].present? || params[:keyword_2].present? || params[:keyword_3].present?
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  require 'httparty'

  def index
    @response = session[:response]
    session.delete(:response)
  end

  def create
    keywords = [params[:keyword_1], params[:keyword_2], params[:keyword_3]].join(" ")
  
    response = HTTParty.post(
      "https://api.openai.com/v1/chat/completions",
      headers: {
        "Authorization" => "Bearer #{ENV['OPENAI_API_SECRET_KEY']}",
        "Content-Type" => "application/json"
      },
      body: {
        messages: [
          {
            role: 'system',
            content: 'You are a helpful assistant.'
          },
          {
            role: 'user',
            content: keywords
          }
        ],
        max_tokens: 50,
        model: "gpt-4-1106-preview"
      }.to_json
    )
    Rails.logger.info "API Response: #{response.parsed_response}"
    session[:response] = response.parsed_response
    redirect_to action: :index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<%#  検索結果を読み込むジャバスクリプト %>
 <script>
  function renderSearchResults(searchQuery) {
    var cx = 'a15bfb6d263eb4a1c';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);

    gcse.onload = function() {
        console.log(google.search.cse.element)
        // ログ表示は後ほど削除
      google.search.cse.element.init({
        div: 'search-list',
        tag: 'searchresults-only',
        attributes: {
          linkTarget: '_blank'
        }
      });

      var searchControl = new google.search.cse.element.CSESearchControl();
      searchControl.execute(searchQuery);
    };
  }

</script>

 
  </head>

  <body>
  <p>search app!
  </p>
    <%= yield %>
  </body>
</html>

app/views/scraps/index.html.erb
<h1 class="text-center my-4">Search Forms***google API***</h1>



<script async src="https://cse.google.com/cse.js?cx=a15bfb6d263eb4a1c">
</script>
<form onsubmit="event.preventDefault(); renderSearchResults(document.getElementById('search-query').value);">
  <input type="text" id="search-query" name="search-query">
  <input type="submit" value="Search">
</form>
<%# <div class="gcse-search"></div> %>
<div class="search-list">
  <% if @response.present? %>
    <ul>
     <% @results.each do |result| %>
    <li><%= result %></li> 
  <% end %>
    </ul>
  <% else %>
    <p>No result found.</p>
  <% end %>
</div>

app/views/searches/index.html.erb
<h1 class="text-center my-4">Search Forms</h1>


<%= form_with url: searches_path, method: :post, local: true, html: { class: 'container' } do |form| %>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="mb-3">
        <label for="search_keyword_1" class="form-label">Search Keyword 1:</label>
        <%= form.text_field :keyword_1, id: "search_keyword_1", class: "form-control" %>
      </div>

      <div class="mb-3">
        <label for="search_keyword_2" class="form-label">Search Keyword 2:</label>
        <%= form.text_field :keyword_2, id: "search_keyword_2", class: "form-control" %>
      </div>

      <div class="mb-3">
        <label for="search_keyword_3" class="form-label">Search Keyword 3:</label>
        <%= form.text_field :keyword_3, id: "search_keyword_3", class: "form-control" %>
      </div>

      <%= form.submit "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<div class="answer text-center my-4">
  <% if @response && @response["choices"] && @response["choices"].first %>
    <p><%= @response["choices"].first["message"]["content"] %></p>
  <% else %>
    <p>No results found.</p>
  <% end %>
</div>